version: '3'
services:
  app:
    platform: linux/x86_64
    build: .
    tty: true
    volumes:
      - ./model:/stable-diffusion/models/ldm/stable-diffusion-v1/
      - ./output:/stable-diffusion/outputs

volumes:
  model:
  output: